#!/bin/bash
echo "Enter Username:"
read username
echo "Enter Domain Name:"
read domainname
echo "Enter IP:"
read ip
sudo mkdir /home/$username/$domainname
sudo cp /etc/apache2/sites-available/template.com /etc/apache2/sites-available/$
sudo cp /home/ubuntu/scripts/htaccesstemplate /home/$username/$domainname/.htac$
sudo sed -i 's/DOMAINNAME/'$domainname'/g' /home/$username/$domainname/.htaccess
sudo sed -i 's/FUCKIP/'$ip'/g' /etc/apache2/sites-available/$domainname
sudo sed -i 's/FUCKDOMAIN/'$domainname'/g' /etc/apache2/sites-available/$domain$
sudo sed -i 's/FUCKUSER/'$username'/g' /etc/apache2/sites-available/$domainname
sudo a2ensite $domainname
sudo service apache2 reload
sudo chown $username:$username /home/$username/$domainname
